### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by mohandhmd** [jerem-ma/pimp_my_lock#1]
Il est ou le readme ?

**Comment by jerem-ma** [comment]
T'as regardé dans le placard a Readme ?

---

Si j'ai une once de motivation, je fais ça aujourd'hui. Encore faut-il que cette motivation se manifeste 👀

**Comment by jerem-ma** [comment]
Aujourd'hui, la motivation m'est apparu. README ajouté dans ce commit 1fd1b16a
