### ISSUE TITLE
Is there a way for the new lock screens?

### ISSUE THREAD

**Issue by EnzoDeg40** [jerem-ma/pimp_my_lock#5]
42 Paris gradually changes `ft_lock` by a new lock called `dm-tool lock`.  I tried changing the bash to try to make it compatible but it seems harder than I think.

**Comment by EnzoDeg40** [comment]
In the end I managed to find a way to customize. but the project has nothing to do with the basic structure of pimp ma lock. So I created a new project : [pimp_my_new_lock](https://github.com/EnzoDeg40/pimp_my_new_lock)

**Comment by jerem-ma** [comment]
Hi!
Is dm-tool lock back in the school? I tried to adapt PML to the new lock tool some months ago, and then, 42Paris reverted the changes and were back to ft_lock.

**Comment by EnzoDeg40** [comment]
Yes the new lock only lasts a few weeks. So for the moment the problem is no longer really present.
